FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Market/Market.csproj", "Market/"]
RUN dotnet restore "Market/Market.csproj"

COPY . .
WORKDIR /src/Market
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 8080

RUN addgroup --system appgrp && adduser --system --ingroup appgrp appusr
USER appusr

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Market.dll"]
